accounts/urls.py
from django.urls import re_path
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls.static import static

app_name='accounts'

urlpatterns = [
    re_path('^login/',views.CustomLoginView.as_view(),name='login'),
    re_path('^logout/',auth_views.LogoutView.as_view(),name='logout'),
    re_path('^signup/',views.SignUp.as_view(),name='signup'),
]

dashboard/urls.py
from django.urls import re_path
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls.static import static
from django.urls import path


app_name='dashboard'

urlpatterns = [
    re_path('enhance/', views.enhance, name='enhance'),
    re_path('ask/', views.ask, name='ask'),
    path('courses/<str:skill_name>/', views.courses, name='courses'),
    path('match/', views.job_description_view, name='match'),
    re_path('', views.main_board, name='dashboard'),  # Put this last
]

resume/urls.py
from django.urls import path
from . import views
app_name='resume'
urlpatterns = [
    # ... your other URLs ...
    path('upload_resume/', views.upload_resume, name='upload_resume'),
]

shellhacks/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from accounts import views
from django.urls import include
from django.conf.urls.static import static
from accounts import views as acc_views
from django.views.generic.base import RedirectView

app_name='myreddit'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='accounts:login'), name='home'),
    re_path('^accounts/',include('accounts.urls',namespace='accounts')),
    re_path('^accounts/',include('django.contrib.auth.urls')),
    re_path('^test/$',views.TestPage.as_view(),name='test'),
    re_path('^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    path('resume/', include('resume.urls')),
    path('dashboard/', include('dashboard.urls',namespace='dashboard')),
    path('about/',acc_views.About.as_view(),name='about')
]

templates/about.html
{% extends 'base.html' %}
{% load static %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link
    href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400&family=Roboto+Condensed:wght@300;400&display=swap"
    rel="stylesheet">
{% block headblock %}
<link rel="stylesheet" href="{% static 'dashboard/css/about.css' %} ">


<div class="about-container">
    <div class="img">
        <img class="log" src="{% static 'logo/finallogo.png' %}">
    </div>
    <div class="page-title">
        CareerGPT   |   Powered by GPT 4
    </div>
    <div class="img2">
        <img class="log" src="{% static 'logo/gpt4.jpeg' %}">
    </div>
    <div class="about-data">
        Introducing CareerGPT, a groundbreaking project powered by the cutting-edge Generative AI, GPT-4. CareerGPT
        revolutionizes the job search and career enhancement experience by allowing users to effortlessly upload their
        resumes
        and tap into a world of transformative features. Whether it's tailoring specific resume sections to match job
        descriptions, discovering top job roles perfectly suited to their skills and aspirations, uncovering strengths
        and
        weaknesses in alignment with desired job positions, engaging in seamless, context-aware conversations with the
        AI model,
        or identifying skills required for their dream roles, CareerGPT empowers individuals to take their career
        journeys to
        new heights. With the added feature of accessing curated resources for upskilling, CareerGPT is your all-in-one
        companion on the road to career success. Welcome to the future of career advancement, where AI meets your
        aspirations
        and guides you toward a brighter future.
    </div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"></script>
  <title>CareerGPT</title>
  <link rel="icon" href="{% static 'logo/finallogo.png' %}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link
    href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400&family=Roboto+Condensed:wght@300;400&display=swap"
    rel="stylesheet">
  {% block headblock %}
  {% endblock %}
  <link rel="stylesheet" href="{% static 'css/master.css' %}">
</head>

<body class="body-whole">


  <nav>

    <div class="nav-left">
      <div class="dp">
        <img class="pic" src="{% static 'logo/finallogo.png' %}">
      </div>
      <a class="navbar-brand" href="{% url 'home' %}">CareerGPT</a>
    </div>

    <div>

      <div class="navbar">
        {% if user.is_authenticated %}
        <form method="post" action="{% url 'dashboard:ask' %}">
          {% csrf_token %}
          <div class="ask">
            <input id="ask-text-input" type="text" name="ask-me-anything" placeholder="Ask me Anything" required>
            <button class="ask-button" type="submit" name="my_button" value="ButtonValue">
              GO
            </button>
          </div>
        </form>

        <a href={% url "resume:upload_resume" %}>Resume</a>
        <a href={% url "dashboard:dashboard" %}>Dashboard</a>
        <a href={% url "dashboard:enhance" %}>Enhance</a>
        <a href={% url "dashboard:match" %}>Match</a>
        <a href={% url "about" %}>About</a>
        <a href={% url "accounts:logout" %}>Logout</a>
        {% else %}

        <a href={% url "accounts:login" %}>Login</a>
        <a href={% url "accounts:signup" %}>Signup</a>
        <a href={% url "about" %}>About</a>
        {%endif%}
      </div>
    </div>
  </nav>
  <div class="mycontent">
    {% block content %}
    {%endblock%}
  </div>
  <script src={% static 'js/master.js' %}></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% block content %}
<h1>Home</h1>
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>You are Logged In</h1>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting resumeguided, come back soon</h1>
{% endblock %}