dashboard/urls.py
from django.urls import re_path
from django.contrib.auth import views as auth_views
from . import views
from django.conf.urls.static import static
from django.urls import path


app_name='dashboard'

urlpatterns = [
    re_path('enhance/', views.enhance, name='enhance'),
    re_path('ask/', views.ask, name='ask'),
    path('courses/<str:skill_name>/', views.courses, name='courses'),
    path('match/', views.job_description_view, name='match'),
    re_path('', views.main_board, name='dashboard'),  # Put this last
]

resume/urls.py
from django.urls import path
from . import views
app_name='resume'
urlpatterns = [
    # ... your other URLs ...
    path('upload_resume/', views.upload_resume, name='upload_resume'),
]

shellhacks/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from accounts import views
from django.urls import include
from django.conf.urls.static import static
from accounts import views as acc_views
from django.views.generic.base import RedirectView

app_name='myreddit'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='accounts:login'), name='home'),
    re_path('^accounts/',include('accounts.urls',namespace='accounts')),
    re_path('^accounts/',include('django.contrib.auth.urls')),
    re_path('^test/$',views.TestPage.as_view(),name='test'),
    re_path('^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    path('resume/', include('resume.urls')),
    path('dashboard/', include('dashboard.urls',namespace='dashboard')),
    path('about/',acc_views.About.as_view(),name='about')
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django import forms

class JobRoleForm(forms.Form):
    role_name = forms.CharField(label='Job Role Name', max_length=255, widget=forms.TextInput(attrs={'placeholder': 'Example: Cloud Engineer'}))
    

class TextInputForm(forms.Form):
    Section = forms.CharField(
        max_length=128,
        widget=forms.TextInput(attrs={'placeholder': 'Example: Experience section'})
    )
    role_company = forms.CharField(
        max_length=128,
        required=False,
        widget=forms.TextInput(attrs={'placeholder': 'Example: Systems Engineer (Optional)'})
    )


from django.core.exceptions import ValidationError

def word_limit(value):
    words = value.split()
    if len(words) > 300:
        raise ValidationError(f'The description has {len(words)} words which is more than the allowed 300 words.')

class JobDescriptionForm(forms.Form):
    description = forms.CharField(widget=forms.Textarea(attrs={'rows':5, 'cols':30}), label="Job Description",validators=[word_limit])

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from . import forms
import openai
import re
from resume import models
openai.api_key = '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'


class chatgptapi:
    def __init__(self):
        self.responsepattern = r'\[(.*?)\]'
    def gen_response(self,inp):
        messages = [{"role":"user","content":inp}]
        chat = openai.ChatCompletion.create(
                    model="gpt-3.5-turbo", messages=messages
                )
        reply = chat.choices[0].message.content
        return reply
    def parse_gpt_response(self,response):
        out = re.findall(self.responsepattern,response)
        return out #dtype = list, list of all values within square braces

@login_required
def main_board(request):
    
    user_resume = models.Resume.objects.filter(user=request.user).first()
    context={}
    # Check if the user's resume exists
    if user_resume:
        
        # Check if job roles exist in the database for this user's resume
        existing_roles = user_resume.job_roles.all()

        if existing_roles:
            roles = [role.role for role in existing_roles]  # Extract job roles from the database entries
        else:
            # If roles don't exist, generate using GPT-3
            chat_api = chatgptapi()

            prompt = user_resume.text_content + ". Use this to suggest the top 3 job roles for this user. Reply with the job roles in python list format. Example - [Full stack developer] , [machine learning engineer], [Computer Vision Researcher]: "
            
            # Generate response using the user's resume text
            gpt_response = chat_api.gen_response(prompt)
            
            # Parse the GPT-3 response
            roles = chat_api.parse_gpt_response(gpt_response)
            for role_name in roles:
                models.JobRole.objects.create(resume=user_resume, role=role_name)

            # Save the generated roles to the database

        if request.method == 'POST':
            role_form = forms.JobRoleForm(request.POST)
            if role_form.is_valid():
                role_name = role_form.cleaned_data['role_name']
                
                chat_api = chatgptapi()
                
                
                
                
                # Further process the concatenated_string if needed
                # For demonstration, we're just printing it
                
                chat_api = chatgptapi()
                prompt = user_resume.text_content +'. This is my Resume. Give top 5 skills that I need to learn for this job and I do not already have in my resume: '+role_name+". Strictly Give the skills in the following format, example - [ AWS ] [ React ] [ CSS ] [ Javascipt ] [ Docker ] ."
                
                gpt_response = chat_api.gen_response(prompt)
                
            # Parse the GPT-3 response
                
                skills = chat_api.parse_gpt_response(gpt_response)
                for i in range(len(skills)):
                    skills[i]=skills[i].strip()
                context['skills']=skills
                # Return a success message or redirect the user if needed
                
        else:
            role_form = forms.JobRoleForm()
        context['roles']=roles
        context['role_form']=role_form
        
        return render(request, 'dashboard/dashboard.html', context)
    


    else:

        # Handle case if the user has not uploaded a resume yet
        return render(request, 'dashboard/dashboard.html', {'message': "Please upload a resume first."})
    
@login_required
def enhance(request):
    user_resume = models.Resume.objects.filter(user=request.user).first()
    if user_resume:
        if request.method == "POST":
            form = forms.TextInputForm(request.POST)
            if form.is_valid():
                entered_text = form.cleaned_data['Section']
                role=form.cleaned_data['role_company']
                chat_api = chatgptapi()
                if len(role)>0:
                    prompt=user_resume.text_content + "Taylor or Reformat the following section of my resume for the following role at the company, use strong action verbs, mention skills and make my resume impressionable to a recruitor hiring for this role, Don't Enter Fake Data that you don't know, just highlight the skills related to the role : "+ entered_text+" "+role 
                else:
                    prompt = user_resume.text_content + "Taylor or Reformat the following section of my resume, use strong action verbs, mention skills and make my resume impressionable to a recruitor : "+ entered_text 
                
                # Generate response using the user's resume text
                gpt_response = chat_api.gen_response(prompt)
                # Here, you can process the text as needed. For now, we'll just redirect.
                return render(request, 'dashboard/enhance.html', {'form': form, 'gpt': gpt_response })   # Redirect to some other view
        else:
            form = forms.TextInputForm()

        return render(request, 'dashboard/enhance.html', {'form': form})
    else:
        return render(request, 'dashboard/enhance.html', {'message': "Please upload a resume first."})
@login_required
def ask(request):
    user_resume = models.Resume.objects.filter(user=request.user).first()
    if user_resume:
        if request.method == 'POST':
            text_value = request.POST.get('ask-me-anything', '')
            
            
            
            if text_value:
                chat_api = chatgptapi()
                prompt=user_resume.text_content+". "+text_value.strip()
                gpt_response = chat_api.gen_response(prompt)
                return render(request, 'dashboard/ask.html', {'gpt': gpt_response}) 
            
                # This will print the value entered in the text input


        # ... rest of the view logic
        return render(request, 'dashboard/ask.html')
    else:
        return render(request, 'dashboard/enhance.html', {'message': "Please upload a resume first."})

class courses_split:
    def __init__(self):
        pass
    def get_separate(self,data):
        entry = data[0:data.find("Intermediate Courses")] 
        intermediate = data[data.find("Intermediate Courses"):data.find("Advanced Courses")]
        adv = data[data.find("Advanced Courses"):]
        return entry,intermediate,adv

@login_required
def courses(request,skill_name):
    user_resume = models.Resume.objects.filter(user=request.user).first()
    print(skill_name)
    if user_resume:

        chat_api = chatgptapi()
        prompt="List 2 Entry Level Courses, 2 Intermediate and 2 Advanced Online Course names with their instructors or company for the following skill : "+skill_name
        gpt_response = chat_api.gen_response(prompt)
        c_s=courses_split()
        entry,inter,adv=c_s.get_separate(gpt_response)

        return render(request, 'dashboard/courses.html', {'course': skill_name, 'entry': entry,'inter':inter,'adv':adv}) 
            
                # This will print the value entered in the text input


        
    else:
        return render(request, 'dashboard/dashboard', {'message': "Please upload a resume first."})
    

from django.shortcuts import render, redirect
class match_split:
    def __init__(self):
        pass
    def get_separate(self,data):
        entry = data[0:data.find("Weaknesses")] 
        adv = data[data.find("Weaknesses"):]
        return entry,adv

def job_description_view(request):
    user_resume = models.Resume.objects.filter(user=request.user).first()
    if user_resume:
        if request.method == "POST":
            form = forms.JobDescriptionForm(request.POST)
            if form.is_valid():
                # Extract job description and perform your operations here
                job_description = form.cleaned_data['description']
                chat_api = chatgptapi()
                prompt=user_resume.text_content+" "+"Analyse my resume and give strengths and weaknesses with regards to the following job description in 100 words. "+job_description+"."
                gpt_response = chat_api.gen_response(prompt)
                m_s=match_split()
                st,wk=m_s.get_separate(gpt_response)
                # ... perform some operations on the job description ...
                
                form = forms.JobDescriptionForm()
                # Redirect or render a template with results or a success message
                return render(request, 'dashboard/match.html', {'form': form, 'st': st,'wk':wk})  # assuming you have a URL named 'success_page'
        else:
            form = forms.JobDescriptionForm()
        return render(request, 'dashboard/match.html', {'form': form})
    else:
        return render(request, 'dashboard/dashboard', {'message': "Please upload a resume first."})
    

templates/dashboard/ask.html
{% extends 'base.html' %}
{% load static %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link
    href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400&family=Roboto+Condensed:wght@300;400&display=swap"
    rel="stylesheet">
{% block headblock %}
<link rel="stylesheet" href="{% static 'dashboard/css/ask.css' %} ">
{% endblock %}
{% block content %}

<div class="ask-response-container">
    <div class="page-title">
        Here is my response for your question...
    </div>
    <div class="ask-response">
        {% if gpt %}
        {{gpt}}
        {% endif %}
    </div>
</div>
{% endblock %}

templates/dashboard/courses.html
{% extends 'base.html' %}
{% load static %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link
    href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400&family=Roboto+Condensed:wght@300;400&display=swap"
    rel="stylesheet">
{% block headblock %}
<link rel="stylesheet" href="{% static 'dashboard/css/ask.css' %} ">
{% endblock %}
{% block content %}

<div class="ask-response-container">
    <div class="page-title">
        {{course}}
    </div>
    <div class="ask-response">
        <h3>{{entry}}</h3>
        <br>
        <h3>{{inter}}</h3>
        <br>
        <h3>{{adv}}</h3>
    </div>
</div>
{% endblock %}

templates/dashboard/dashboard.html
{% extends 'base.html' %}
{% load static %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link
    href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400&family=Roboto+Condensed:wght@300;400&display=swap"
    rel="stylesheet">
{% block headblock %}
<link rel="stylesheet" href="{% static 'dashboard/css/dashboard.css' %} ">
{% endblock %}
{% block content %}

<div class="dash-main">
    <div class="dash-title">
        <ul>
            <li>Best roles for you</li>
        </ul>
    </div>
    <div class="roles">
        {% if roles %}
        <div class='role-main'>
            {% for role in roles %}
            <div class='{% if forloop.last %}each-role2{% else %}each-role{% endif %}'>
                <p class='role'>
                    {{ role }}
                </p>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="skill-gap">
        <!-- Add the new Job Role Form -->
        <div class="dash-title">
            <ul>
                <li>Skill Gap Analysis: Bridging the Path to Success</li>
            </ul>
        </div>
        <form method="post">
            {% csrf_token %}
            {{ role_form.as_p }}
            <div class="button-div">
                <input type="submit" value="Find Gap">
            </div>
        </form>
        {%if skills %}
        <div class="skills-upgrade-div">

        <div class="dash-subtitle">
            Explore Your Learning Journey: Discover Resources to Master These Essential Skills. Each skill listed below is a valuable asset on your learning path. Click on each link to access a wealth of resources that will help you get started and become a proficient master of each skill.
        </div>
        <div class="skills-upgrade-container">
        {% for skill in skills %}
        <a href="{% url "dashboard:courses" skill_name=skill %}"">
        <div class="skill-button">
        {{ skill }}
        </div>
        </a>
        {% endfor %}
        </ul>
        </div>
        {% endif %}
        </div>
        {% else %}
        <h2>{{ message }}</h2>
        {% endif %}
    </div>
</div>

{% endblock content %}

templates/dashboard/enhance.html
{% extends 'base.html' %}
{% load static %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link
    href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400&family=Roboto+Condensed:wght@300;400&display=swap"
    rel="stylesheet">
{% block headblock %}
<link rel="stylesheet" href="{% static 'dashboard/css/enhance.css' %} ">
{% endblock %}
{% block content %}

<div class="enhance-container">
    {%if form %}
    <div class="enhance-form">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="button-div">
                <button class="mybutton" type="submit">Submit</button>
            </div>
        </form>
    </div>
    <div class="enhance-answer">
        {% if gpt %}
        {{gpt}}
        {% endif %}
        
    </div>
    {%else%}
    <h1>{{message}}</h1>
    {%endif%}
</div>
{% endblock %}

templates/dashboard/match.html
{% extends 'base.html' %}
{% load static %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link
    href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;400&family=Roboto+Condensed:wght@300;400&display=swap"
    rel="stylesheet">
{% block headblock %}
<link rel="stylesheet" href="{% static 'dashboard/css/match.css' %} ">
{% endblock %}
{% block content %}

<div class="match-container">
    <div class="page-title">
        Assess Your Strengths and Weaknesses in Alignment with the Job Description
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="button-div">
            <button class="mybutton" type="submit">Submit</button>
        </div>

    </form>


    {% if st %}
    <div class="ask-response">
        {{st}}
        <br><br> <br>
        {{wk}}

    </div>
</div>
{%endif%}


</div>


{% endblock %}